[project]
name = "Portfolio-Balancer"
version = "1.0.1"
description = "Tool to keep balance a portfolio of securities while investing."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pyscipopt",
    "cvxpy",
    "gradio",
    "pandas",
    "matplotlib",
    "pyQt6",
    "yfinance",
    "ecbdata",
]
